language: php

matrix:
  include:
    - php: 7.1
    - php: 7.0
    - php: 5.6
    - php: 5.5
    - php: 5.4
    - php: 5.3

addons:
  apt:
    packages:
      - parallel

sudo: false

script:
   - >
     echo "Running php lint";
     find . -name \*.php | parallel --gnu php -d display_errors=stderr -l {} > /dev/null \;
